# .github/workflows/release.yaml
name: Release xMLTree Editor

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            exe_name: xMLTree-linux
            script_path: src/xMLTree.py
            built_file: dist/xMLTree

          - os: windows-latest
            exe_name: xMLTree.exe
            script_path: src\\xMLTree.py
            built_file: dist\\xMLTree.exe

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --windowed ${{ matrix.script_path }}

      - name: Rename output file (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: mv ${{ matrix.built_file }} dist/${{ matrix.exe_name }}

      - name: Rename output file (Windows)
        if: matrix.os == 'windows-latest'
        run: ren ${{ matrix.built_file }} ${{ matrix.exe_name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/${{ matrix.exe_name }}
            assets/xMLTree-linux.png
          draft: false
          prerelease: false
